# Generated by Django 5.2 on 2025-07-31 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_app', '0002_area_customer_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_for_month',
            field=models.IntegerField(blank=True, help_text='Month number (1-12) this payment is for', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_for_year',
            field=models.IntegerField(blank=True, help_text='Year this payment is for', null=True),
        ),
        migrations.CreateModel(
            name='MonthlyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(help_text='Month number (1-12)')),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_balances', to='dairy_app.customer')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('customer', 'year', 'month')},
            },
        ),
    ]
