# Generated by Django 5.2 on 2025-08-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_app', '0004_paymentallocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['area', 'delivery_order', 'name']},
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_order',
            field=models.PositiveIntegerField(default=0, help_text='Order for delivery route within area'),
        ),
    ]
