X XXXXXXXXX XXXXXXXX XXX XXXXX XXXXXXX XXXXXXXXXX
XXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXX

X XXXXXXXXXX XXXXXX
XXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXX

X XXXXXXXX XXXXXX XXX XXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX

X XXX XXXXXXXXXX
XXXXXXXXXXXXXXXX
XXXXXXXXXXXXX

X XXXXX XXXXXX
XXXXXXXXXXX

X XXXXXXXXXXX XXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX

X XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXX XXX XXXXXX XXX XXXXXXXX
XXXXXXXXXXXXXX
XXXXXXXXXXXXXXX
XXXXXXXXXXXXXX

X XXXXX XXXXXXX XXXXXXXX XXX XXXX XX XXXXXXXXXXX
X X XXXXXXXXXXXXXX XXXX XXXX XX XXX XXXX
X X XXXXXXXXX XXXXXXXXXXX XX XXXXXXXXXXXXXXX
X X XXXXXXXXXXXXXXX XXXX XXXXX XXXXX XXXXXX XX XXXXXXX
X X XXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXX XXX XXXXXX
X X XXXXXXXXX XXXXXXXXXXXXXXXXX
X X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXX XXXXXX XXXXXXXXX
