XXXXXXXXX XXXXX
XXXXX XXXXXXBB BBBBBBBBBBBBBBBBBXXBBBBBXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    BBBB BBBB
    XXXXXXXBBBBB BBBBB gettext(u'Shree Trimurti Dairy') BBBBBBBBXXXXXXXX
    
    XXXX XXXXXXXXX XXX XXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    
    XXXX XXXX XXXXXXX XXX XXXXX XXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXX XXX XXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX
        XXXXX X
            XXXXXXXXXXXXXXXX XXXXXXXX  XX XXXXX XX
            XXXXXXXXXXXXXXX XXXXXXXX   XX XXXXX XX
            XXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
        X
        
        XXXX X
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XX XXX XXXXXXX XXXXXX XXX XXXXXX XX XXXXXXX XXX XXX XXXXXX XXX XXX XX
            XXXXXXXXXXXXXXX XXXXX
        X
        
        XXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXX X
            XXXXXXXXXXXX XXXXX
        X
        
        XXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXX X XXXXXX
            XXXXXXXXXXXXXX XX
            XXXXXXXXXXXXX XX
        X
        
        XXXXXXXX XXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXXXXX
        X
        
        XXXXXXXX XXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX
        X
        
        XXXXXXXX XXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX
        X
        
        XXXXXXXX XXXXXXXXX X X
            XXXXXXXXXXXXX XXXXXXX
            XXXXXX XXXXX
            XXXXXXXXXXX XXXXXXX
        X
        
        XXXXX X
            XXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXX X XXXXXXXX XXXXXXX XXXXXXX XX XX XXXXXXX
        X
        
        XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXX
        X
        
        XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXX
            XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXX
        X

        XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXX
        X
        
        XXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXX  XX XXX XX
            XXXXXXXXXXXX XXXXX
        X
        
        XXXXXXXXXXXXX X
            XXXXX XX
            XXXXXXXX XXXXXXX
        X
        
        XXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXX XX
            XXXXXXXXXXX XXXXX
        X
        
        XX XXXXXX XXXXX XXX XXXXXXXXX XX
        XXXXXXXXXXX X
            XXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXX XXXXX
        X
        
        XXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXX XXXXXXXXXX X
            XXXXXXXX XXXXX
        X
        
        XXXXXXXXXXX XXXXXXXXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXX XXXXXXXX
            XXXXXXXXXXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXX XXXXXXXXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XX
        X
        
        XXXXXXXXXXX XXXXXXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX
        X

        XX XXXXXXXXX XXXX XXXXXX XX
        XXXXXXXXXXXXXXX X
            XXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXX XXXXX
        X
        
        X XXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXX XXXXX
        X
        
        X XXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
        X
        
        X XXXXXXXXXXXXXXX XXXXXXXXXXXX
        X XXXXXXXXXXXXXXX XXXXXXXXXXXX
        X XXXXXXXXXXXXXXX XXXXXXXXXXX X
            XXXXXX XXXXXXXX
        X

        XX XXXXXX XXXXXX XXXXXXXXXX XXX XX
        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXX XXXXXX
            XXXXXXX XX
            XXXXX XX
            XXXXXX XX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXX
        X

        XXXXXXXXXXXXXXXXXX XXXXXXXXX X
            XXXXX XX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXX XXXX XXXX XXXXX
            XXXXXXXX XXX XXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXXXXX
            XXXXXXXXXXX XXX XXXXX
            XXXXXXXXXX XX
        X

        XXXXXXXXXXXXXXXXXX XXXXXXXXX X X
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXXX
        X

        XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX X
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXX XXXXX
        X

        XX XXXX XXXXX XXXXXXX X XXXX XXXX XXXXXX XX
        XXXXXX XXXXXXXXXXX XXXXXX X
            XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX X
                XXXXXXXX XXXXX
            X
            XXXXXXXXXXXXXXXXXX XXXXXXXXX X X
                XXXXXXXXXX XXXXXXX
                XXXXXXXXXXXXXX XX
            X
            XXXXXXXXXXXXXXXXXX XXXXXXXXX X
                XXXXXXXX XXXX XXXX
            X
        X

        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        X

        XX XXXX XX XXXXXX XXXXXXX XX
        XXXXXX XXXXXXXXXXX XXXXXX X
            XXXXXXXXXXXXXXXXXX X
                XXXXXXXX XXXXX
            X
            XXXX X
                XXXXXXXXXXXXXXX XX
            X
        X
        
        XX X XXXXXX XXXXXX XXXXXXX XX
        XXXXXXXXXXXXXXXXXX XXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XXXXXXXXXXX XXX XXXX XXXXX
            XXXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXX X XXX XXX XXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXX XXXX
            XXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXXXXXXXX
        X
        
        XX XXXXXX XXXXX XXXXXXXXXXXX XX
        XXXXXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXX XXXX
        X
        
        XXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXX XXXX
        X
        
        XXXXXXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XX XXXXXXX XXXX XXXXXX XXXXXXX XX
        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXX XXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXX
        X
        
        XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXX XXXX X
            XXXXXXXXXXX XXX XXXX XXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXX X XXX XXX XXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
            XXXXXXXX XXXX
            XXXXXXX XXXXXXXXXXXX
        X
        
        XXXXXXXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXX
        X
        
        XX XXXXXXXX XXXXXXXXXX XXXXXXXXX XX
        XXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXXX
        X
    XXXXXXXX
    
    BBBBB BBBBBBBBBBBBBBBBB
XXXXXXX
XXXXXX
    XXXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Shree Trimurti Dairy') 
            XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXX XXXXXXXXXX XXXXX XXXXXXX XX XXXXXX XXX XXXXXXX XXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                        XX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Dashboard') 
                        XXXX
                    XXXXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                        XX XXXXXXXXXXXXXXX BB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Areas') 
                        XXXX
                    XXXXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                        XX XXXXXXXXXXXXXXX BB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Customers') 
                        XXXX
                    XXXXX

                    XXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                        XX XXXXXXXXXXXXXXX BB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBBXX
                            XX XXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Milk Types') 
                        XXXX
                    XXXXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                        XX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBBBXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Customer Data Export') 
                        XXXX
                    XXXXX
                    BBBBB
                XXXXX
                XXX XXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBB
                    XXX XXXXXXXXXXXXXXX XXXXXX
                        XX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBBBXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Export data') 
                        XXXX
                    XXXXX
                    XXXX XXXXXXXX XXXXXXXX X XXXXXXX XXXXXXX XXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX
                        XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXX BB BBBBBBBBBBBBB BB BBBB gettext(u'English') BBBB BBBBBBBBBBBBB BB BBBB gettext(u'हिंदी') BBBB BBBBBBBBBBBBB BB BBBB gettext(u'मराठी') BBBBFFFFFBBBBB
                        XXXX
                        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            BBBB BBBB
                            BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
                            BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB
                            BBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBB BB BBBBBBBBB
                            
                            BBB BBBBBBBB BB BBBBBBBBB
                            XXXX
                                XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                    BBBBBBBBBB
                                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXBBBBBXX
                                        BB BBBBBBBBBBBBB BB BBBB
                                            XX XXXXXXXXXX XXXXXXXX XXXX BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXXXBBBBBXXXXXX  gettext(u'English') 
                                        BBBB BBBBBBBBBBBBB BB BBBB
                                            XX XXXXXXXXXX XXXXXXXX XXXX BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXXXBBBBBXXXXXX  gettext(u'हिंदी') 
                                        BBBB BBBBBBBBBBBBB BB BBBB
                                            XX XXXXXXXXXX XXXXXXXX XXXX BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXXXBBBBBXXXXXX  gettext(u'मराठी') 
                                        BBBB
                                            XX XXXXXXXXXX XXXXXXXX XXXX BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXXXBBBBBXXXXXX 
                                        BBBBB
                                    XXXXXXXXX
                                XXXXXXX
                            XXXXX
                            BBBBBB
                        XXXXX
                    XXXXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXXXX
                        XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX 
                        XXXX
                        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Admin') XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX
                                XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBX XXXXXXXXXXXXXX XXXX
                                    BBBBBBBBBB
                                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Logout') XXXXXXXXX
                                XXXXXXX
                            XXXXX
                        XXXXX
                    XXXXX
                    BBBB
                    XXX XXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBXX gettext(u'Login') XXXX
                    XXXXX
                    BBBBB
                XXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    
    XXXX XXXX XXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXX XXX
            BB BBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX
                    XXX XXXXXXXXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBXX
                                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Dashboard') 
                            XXXX
                        XXXXX
                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXX BB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBXX
                                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Areas') 
                            XXXX
                        XXXXX
                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXX BB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBXX
                                XX XXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Customers') 
                            XXXX
                        XXXXX

                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXX BB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBBXX
                                XX XXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Milk Types') 
                            XXXX
                        XXXXX
                    XXXXX
                XXXXXX
            XXXXXX
            BBBBB
            
            XXXX XXXX XXXXXXX XXX
            XXXXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXBBBBXXXXXXBBBBB XXXXXXXXXXXXXX
                BB BBBBBBBB
                XXXX XXXXXXXXXXXXXXXXX
                    BBB BBBBBBB BB BBBBBBBB
                    XXXX XXXXXXXXXXXX BB BBBBBBBBBBBBXXXXXXBBBBXXXXXXXXXXBBBBB XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
                        
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    BBBBBB
                XXXXXX
                BBBBB
                
                BBBBB BBBBBBB
                XXXX XXXX XXXXXXX XXXX XXXX XXX
                BBBBBBBB
            XXXXXXX
        XXXXXX
    XXXXXX
    
    XXXX XXXXXX XXXXXX XXXXXXXXXX XXX XXX
    BB BBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX gettext(u'Dashboard') XXXXXXX
        XXXX
        XX XXXXXXXXXXXXXXX BB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX gettext(u'Areas') XXXXXXX
        XXXX
        XX XXXXXXXXXXXXXXX BB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBXX
            XX XXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX gettext(u'Customers') XXXXXXX
        XXXX
        XX XXXXXXXXXXXXXXX BB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBBXX
            XX XXXXXXXXXX XXXXXXXXXXXXX
            XXXXXX gettext(u'Milk Types') XXXXXXX
        XXXX
    XXXXXX
    BBBBB
    
    XXXX XXXXXX XXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Proudly Developed by') XXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                            XXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXX
                                XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXX XXXXX
                            XXXXXXX
                        XXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXX
    
    XXXX XXXXXXXXX XX XXXXXX XXXX XXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXXXXXX
        XX XXXXX XXX XXXX XXXXXXXXX XXXXXX XXXXXXXX XXXX XXXXXXXXX XX XXXXXX XXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XX XXXXXXXXXXXXXXXXXX X XXXX X
                XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                    XXXXX XXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                        XXXXXXX XXXXX
                    XXX
                    XXXXXXXXXXXXXXXXXX
                X
            X
        XXX
        
        XX XXXXXX XXXXXX XXXXXXXXXX XXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            
            XXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXX XX XXXXXXXXXXXX XXX XXXX XX XXXXX XXX XXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X XXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
            XXX
        XXX
    XXXXXXXXX
    
    BBBBB BBBBBBBBBBBBBBB
XXXXXXX
XXXXXXX