XXXXXXXXX XXXXX
XXXXX XXXXXXBB BBBBBBBBBBBBBBBBBXXBBBBBXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXBBBBB BBBBBXXXXXXXX XXXXXBBBBBBBBXXXXXXXX
    
    XXXX XXXXXXXXX XXX XXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    
    XXXX XXXX XXXXXXX XXX XXXXX XXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXX XXX XXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX
        XXXXX X
            XXXXXXXXXXXXXXXX XXXXXXXX  XX XXXXX XX
            XXXXXXXXXXXXXXX XXXXXXXX   XX XXXXX XX
            XXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
        X
        
        XXXX X
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XX XXX XXXXXXX XXXXXX XXX XXXXXX XX XXXXXXX XXX XXX XXXXXX XXX XXX XX
            XXXXXXXXXXXXXXX XXXXX
        X
        
        XXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXX X
            XXXXXXXXXXXX XXXXX
        X
        
        XXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXX X XXXXXX
        X
        
        XXXXXXXX XXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXXXXX
        X
        
        XXXXXXXX XXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX
        X
        
        XXXXXXXX XXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX
        X
        
        XXXXXXXX XXXXXXXXX X X
            XXXXXXXXXXXXX XXXXXXX
            XXXXXX XXXXX
            XXXXXXXXXXX XXXXXXX
        X
        
        XXXXX X
            XXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXX X XXXXXXXX XXXXXXX XXXXXXX XX XX XXXXXXX
        X
        
        XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXX
        X
        
        XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXX
        X

        XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXX
        X
        
        XXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXX  XX XXX XX
            XXXXXXXXXXXX XXXXX
        X
        
        XXXXXXXXXXXXX X
            XXXXX XX
            XXXXXXXX XXXXXXX
        X
        
        XXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXX XX
            XXXXXXXXXXX XXXXX
        X
        
        XX XXXXXX XXXXX XXX XXXXXXXXX XX
        XXXXXXXXXXX X
            XXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXX XXXXX
        X
        
        XXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXX XXXXXXXXXX X
            XXXXXXXX XXXXX
        X
        
        XXXXXXXXXXX XXXXXXXXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXX XXXXXXXX
            XXXXXXXXXXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXX XXXXXXXXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XX
        X
        
        XXXXXXXXXXX XXXXXXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX
        X

        XX XXXXXX XXXXXX XXXXXXXXXX XXX XX
        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXX XXXXXX
            XXXXXXX XX
            XXXXX XX
            XXXXXX XX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXX
        X

        XXXXXXXXXXXXXXXXXX XXXXXXXXX X
            XXXXX XX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXX XXXX XXXX XXXXX
            XXXXXXXX XXX XX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXX XXX XXXXX
        X

        XXXXXXXXXXXXXXXXXX XXXXXXXXX X X
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXXX
        X

        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        X

        XX XXXX XX XXXXXX XXXXXXX XX
        XXXXXX XXXXXXXXXXX XXXXXX X
            XXXXXXXXXXXXXXXXXX X
                XXXXXXXX XXXXX
            X
            XXXX X
                XXXXXXXXXXXXXXX XX
            X
        X
    XXXXXXXX
    
    BBBBB BBBBBBBBBBBBBBBBB
XXXXXXX
XXXXXX
    XXXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX
            XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXX XXXXXXXXXX XXXXX XXXXXXX XX XXXXXX XXX XXXXXXX XXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                        XX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                        XXXX
                    XXXXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                        XX XXXXXXXXXXXXXXX BB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
                        XXXX
                    XXXXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                        XX XXXXXXXXXXXXXXX BB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
                        XXXX
                    XXXXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                        XX XXXXXXXXXXXXXXX BB BBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX
                        XXXX
                    XXXXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                        XX XXXXXXXXXXXXXXX BB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBBXX
                            XX XXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXX
                        XXXX
                    XXXXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                        XX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX
                        XXXX
                    XXXXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                        XX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBBXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX
                        XXXX
                    XXXXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                        XX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBBBXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXX
                        XXXX
                    XXXXX
                    BBBBB
                XXXXX
                XXX XXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBB
                    XXX XXXXXXXXXXXXXXX XXXXXX
                        XX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBBBXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXX
                        XXXX
                    XXXXX
                    XXXX XXXXXXXX XXXXXXXX X XXXXXXX XXXXXXX XXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX
                        XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXXXBBBB BBBBBBBBBBBBB BB BBBBXXXXXBBBBFFFFFBBBBB
                        XXXX
                        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            BBBB BBBB
                            BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
                            BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB
                            BBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBB BB BBBBBBBBB
                            
                            BBB BBBBBBBB BB BBBBBBBBB
                            XXXX
                                XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                    BBBBBBBBBB
                                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXFFFFFFFFFFXX
                                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXBBBBBXX
                                        BB BBBBBBBBBBBBB BB BBBB
                                            XX XXXXXXXXXX XXXXXXXX XXXX BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXXXBBBBBXXXXXX XXXXXXX
                                        BBBB BBBBBBBBBBBBB BB BBBB
                                            XX XXXXXXXXXX XXXXXXXX XXXX BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXXXBBBBBXXXXXX XXXXX
                                        BBBB
                                            XX XXXXXXXXXX XXXXXXXX XXXX BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXXXBBBBBXXXXXX 
                                        BBBBB
                                    XXXXXXXXX
                                XXXXXXX
                            XXXXX
                            BBBBBB
                        XXXXX
                    XXXXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXXXX
                        XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX 
                        XXXX
                        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX
                                XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBX XXXXXXXXXXXXXX XXXX
                                    BBBBBBBBBB
                                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXX
                            XXXXX
                        XXXXX
                    XXXXX
                    BBBB
                    XXX XXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBXXXXXXXXXXX
                    XXXXX
                    BBBBB
                XXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    
    XXXX XXXX XXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXX XXX
            BB BBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX
                    XXX XXXXXXXXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBXX
                                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXX
                        XXXXX
                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXX BB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBXX
                                XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
                            XXXX
                        XXXXX
                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXX BB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBXX
                                XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
                            XXXX
                        XXXXX
                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXX BB BBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBXX
                                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX
                            XXXX
                        XXXXX
                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXX BB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBBXX
                                XX XXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXX
                            XXXX
                        XXXXX
                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                            XXXX
                            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                XXX XXXXXXXXXX XXXXXXXXXXX XXXXXX
                                    XXX XXXXXXXXXXXXXXXXX
                                        XX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBXX
                                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX
                                        XXXX
                                    XXXXX
                                    XXX XXXXXXXXXXXXXXXXX
                                        XX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBBXX
                                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX
                                        XXXX
                                    XXXXX
                                XXXXX
                            XXXXXX
                        XXXXX
                    XXXXX
                XXXXXX
            XXXXXX
            BBBBB
            
            XXXX XXXX XXXXXXX XXX
            XXXXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXBBBBXXXXXXBBBBB XXXXXXXXXXXXXX
                BB BBBBBBBB
                XXXX XXXXXXXXXXXXXXXXX
                    BBB BBBBBBB BB BBBBBBBB
                    XXXX XXXXXXXXXXXX BB BBBBBBBBBBBBXXXXXXBBBBXXXXXXXXXXBBBBB XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
                        
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    BBBBBB
                XXXXXX
                BBBBB
                
                BBBBB BBBBBBB
                XXXX XXXX XXXXXXX XXXX XXXX XXX
                BBBBBBBB
            XXXXXXX
        XXXXXX
    XXXXXX
    
    XXXX XXXXXX XXXXXX XXXXXXXXXX XXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        XXXX
        XX XXXXXXXXXXXXXXX BB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBXX
            XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
        XXXX
        XX XXXXXXXXXXXXXXX BB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
        XXXX
        XX XXXXXXXXXXXXXXX BB BBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX
        XXXX
        XX XXXXXXXXXXXXXXX BB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBBXX
            XX XXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXX
        XXXX
    XXXXXX
    
    XXXX XXXXXX XXX
    XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXX XXXX XXXXXXXX XXXXX X XXXXXXXXX XXX XXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXX
        XXXXXX
    XXXXXXXXX
    
    XXXX XXXXXXXXX XX XXXXXX XXXX XXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    BBBBB BBBBBBBBBBBBBBB
XXXXXXX
XXXXXXX