BBBBBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Area Customers')  X  gettext(u'Shree Trimurti Dairy') BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX gettext(u'Customers in')  XXXXX
            XX XXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX 
                 gettext(u'Drag and drop customers to reorder them for delivery route') 
            XXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Add Customer to This Area') 
            XXXX
        XXXXXX
    XXXXXX

    BB BBBBBBBB
    XXXX XXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXX
            BBB BBBBBBB BB BBBBBBBB
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
            BBBBBB
        XXXXXX
    XXXXXX
    BBBBB

    XXXX XXXXX XXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXX XXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXX gettext(u'Success') XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                 gettext(u'Customer delivery order updated successfully!') 
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXX gettext(u'Delivery Route Order') XXXXX
                XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Back to Areas') 
                XXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            BB BBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Saving...') XXXXXXX
                XXXXXX
                XX XXXXXXXXXXXXX gettext(u'Updating delivery order...') XXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXX
                            XXX XXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXX gettext(u'Drag to reorder') XXXXXX
                            XXXXX
                            XXXXXXXXXX
                            XXXX gettext(u'Name') XXXXX
                            XXXX gettext(u'Phone') XXXXX
                            XXXX gettext(u'Address') XXXXX
                            XXXX gettext(u'Actions') XXXXX
                        XXXXX
                    XXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        BBB BBBBBBBB BB BBBBBBBBB
                        XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
                            XXXXX
                            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX
                            XXXXFFFFFFFFFFFXXXXX
                            XXXXFFFFFFFFFFFXXXXX
                            XXXX
                                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                    XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXX
                                        XX XXXXXXXXXX XXXXXXXXXXXX  gettext(u'View') 
                                    XXXX
                                    XX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
                                        XX XXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Edit') 
                                    XXXX
                                XXXXXX
                            XXXXX
                        XXXXX
                        BBBBBB
                    XXXXXXXX
                XXXXXXXX
            XXXXXX
            BBBB
            XXXX XXXXXXXXXXXX XXXXXXXXXXXX
                 gettext(u'No customers are assigned to this area yet.') 
                XX XXXXXXBBB BBBBBBBBBBBBBBXXXXXXX XXXXXXXXXXXXXXXXXXX
                     gettext(u'Add a customer to this area') 
                XXXXX
            XXXXXX
            BBBBB
        XXXXXX
    XXXXXX
XXXXXX

XXXXXXX
XX XXXX XXX XXXX XXXXXX XX
XXXXXXXXXXXXXX X
    XXXXXXXXXXX XXX XXXX XXXXX
X

XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXX
    XXXXXXXXXX XXXXXXXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXX XXXXX XXXXXXXX
X

XXXXXXXXXXXX X
    XXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXXXXXXX
X

XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX
X

XXXXXXXXXXXXXXX X
    XXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
X

XX XXXXXXX XXXXX XX
XXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
X
XXXXXXXX

XXXXXXXX
XX XXX XXXX XX XX X XXXXXX XXXXXXXX
XXXXXXXXXXXXX X X
XXXXXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXX XXXXXXXXXXXXXX X XXXXX
    XXX XXXXXXXXXXXX X XXXXX

    XX XXX XXXXX XXXXXXXXX XX XXX XXXXXXXXX XXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXXXXXXXXXXXXXXX XXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
                XXXXXXXXXXXXXX X XXXXX
                XXXXXXXXXXXX X XXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXX

            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX X XXXXX
                XXXXXXXXXXXX X XXXXX
                
                XX XXXXXX XXXXXXXXX XXXXX XXXX XXX XXXX
                XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX

            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
                
                XX XXXXX XXX XXXXXXXXXXXXXXX X
                    XX XXXXXX XXXXXXXXX XXXXX XXXX XXX XXXX
                    XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
            XXX

            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXX
            XXX

            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
                XX XXXX XXXXXX XXXXXXXXX XX XXXXX XXXXXXX XXX XXXXXXX XXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
            XXX

            XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXX
                
                XX XXXXX XXX XXXXXXXXXXXXXXX X
                    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    
                    XX XXXXXXXXXXXXX X XXXXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    X XXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                    X
                    
                    XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXX
                X
                
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX
        XXX
    X

    XX XXXXXX XXX XXXXXXXX XXXXX XXXXXXX XX XXX XX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX X XX
        XXX
    X

    XX XXXX XXX XXX XXXXX XX XXX XXXXXX
    XXXXXXXX XXXXXXXXXXXXXX X
        XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXX XXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBXX X
            XXXXXXX XXXXXXX
            XXXXXXXX X
                XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX XXX
            XX
            XXXXX XXXXXXXXXXXXXXXX
                XXXXXXXXXXXXX XXXXXXXXXXXX
                XXXXXXXX XXXXXXXXXXXXX
            XX
        XX
        XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
        XXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XX XXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXX
            X XXXX X
                XXXXXXX gettext(u'Error updating customer order') X X X XXXXXXXXXXXX
                XX XXXXXX XXX XXXX XX XXXXX XXX XXXXX
                XXXXXXXXXXXXXXXXXX
            X
        XX
        XXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXX gettext(u'Error updating customer order') XXX
            XX XXXXXX XXX XXXX XX XXXXX XXX XXXXX
            XXXXXXXXXXXXXXXXXX
        XXX
    X

    XX XXXXXXXXXX XXXX XXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX
XXX
XXXXXXXXX
BBBBBBBB
