BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Customers - Dairy Manager') BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX  gettext(u'Customers') XXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Add Customer') 
            XXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXX XXXXXX XXX XXX
XXXX XXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'Search Customer') XXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX 
                           XXXXXXXXXXXXX gettext(u'Search by customer name...') X XXXXXXXX XXXXXXXXXX
                    BB BBBBBBBBBBBB
                    XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Clear') 
                    XXXXXXXXX
                    BBBBB
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Searching...') 
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXXXXX
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XX XXXXX XXXXXXXXXX XXX XXXXXX XX
        XXXXXX XXXXXXX XXXXXXXXXXX XX XXXX XXXXX XXXX XXX XXXXXX XXXXXXXX XX
    X
    
    XXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXX XXXXXXX XXXXXXXXXXX
    X
    
    XX XXXXXXXXXX XXXXXX XX
    XXXXXXXXXX X
        XXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXX XXXXXXXX
    X
    
    XXXXXXXXXXXXXXXX X
        XXXXXXXXXXX X X X XXXXXXX XXXXXXXX XXXX XXX XXXXXX
    X
    
    XX XXXXXX XXXXXXXXXXXX XXXXXX XX
    XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXX X XXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXXXX XXXXX
    X
XXXXXXXX

XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXX gettext(u'Customer List') XXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBB
                XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Total') X   gettext(u'customers') XXXXXXX
                BBBBB
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXX
                    XXXX
                        XXXX gettext(u'Sr.No.') XXXXX
                        XXXX gettext(u'Name') XXXXX
                        XXXX gettext(u'Milk Types') XXXXX
                        XXXX gettext(u'Total Milk Delivered')  XXXXXXX
                        XXXX gettext(u'Balance')  XXXXXXXX
                        XXXX gettext(u'Actions') XXXXX
                    XXXXX
                XXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBB BBBBBBBB BB BBBBBBBBB
                    XXXX
                        XXXXXXXXX
                        XXXX
                            XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            BB BBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBB
                                FFFF
                            BBBB
                                
                            BBBBB
                            XXXX
                        XXXXX
                        XXXX
                            BBB BBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
                            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                            BBBBB
                            XXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX gettext(u'None') XXXXXXX
                            BBBBBB
                        XXXXX
                        XXXX
                            BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                BB BBBBBBBBBBBBBBBBB
                                    BBB BBBBBBBBBBBBBBB BBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
                                        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                            X FFFFFFFFFFFFF  gettext(u'L') 
                                        XXXXXXX
                                    BBBBBB
                                BBBB
                                    XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'No deliveries') XXXXXXX
                                BBBBB
                            BBBBBBB
                        XXXXX
                        XXXX
                            BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                XXXXX XXXXXXXXXXXX BB BBBBBBB B BXXXXXXXXXXBBBB BBBBBBB B BXXXXXXXXXBBBBXXXXXXXX XXXXXXXXXBBBBB XXXXXX
                                    XFFFFFFFFFFFFF
                                XXXXXXX
                            BBBBBBB
                        XXXXX
                        XXXX
                            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                XX XXXXXXBBB BBBBBBBBBBXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Sale') 
                                XXXX
                                XX XXXXXXBBB BBBBBBBBBBBBBXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Payment') 
                                XXXX
                            XXXXXX
                        XXXXX
                    XXXXX
                    BBBBBB
                XXXXXXXX
            XXXXXXXX
        XXXXXX
        
        XXXX XXXXXXXXXX XXXXXXXX XXX
        BB BBBBBBBBBBBB
        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBB
                    XXX XXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXBB BBBBBBBBBBBBXXXXXXXXBBBBBX XXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX
                    XXXXX
                    XXX XXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXBB BBBBBBBBBBBBXXXXXXXXBBBBBX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX
                    XXXXX
                    BBBBB
                    
                    BBB BBBBBBBB BB BBBBBBBBBB
                        BB BBBBBBBB BB BBBBB
                            XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        BBBB
                            XXX XXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBXXXXXXBBBBBXX
                                XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXBB BBBBBBBBBBBBXXXXXXXXBBBBBXXXXXX
                            XXXXX
                        BBBBB
                    BBBBBB
                    
                    BB BBBBBBBBBBBBBBBBB
                    XXX XXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXBB BBBBBBBBBBBBXXXXXXXXBBBBBX XXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX
                    XXXXX
                    XXX XXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXBB BBBBBBBBBBBBXXXXXXXXBBBBBX XXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX
                    XXXXX
                    BBBBB
                XXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX
             gettext(u'Showing')  X  gettext(u'of')    gettext(u'customers') 
        XXXXXX
        BBBBB
        
        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXX
            XX XXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXX
            XX XXXXXXXXXXXXX gettext(u'No customers found') XXXX
            XX XXXXXXXXXXXXXXXXXXX gettext(u'No customers match your search') X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Clear Search') 
            XXXXXXXXX
        XXXXXX
        BB BBB BBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXX XXXXXX
            XX XXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXX
            XX XXXXXXXXXXXXX gettext(u'No customers found') XXXX
            XX XXXXXXXXXXXXXXXXXXX gettext(u'Add customers to start recording sales and payments') XXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Add Customer') 
            XXXX
        XXXXXX
        BBBBB
    XXXXXX
XXXXXX

XXXXXXXX
XX XXXXXXXX XXXXXXXX XX XXXXX XXX XXXXX XXX XXXXXX XX XXXXXXXXX
XXXXXXXX XXXXXXXXXXXXXX XXXXX X
    XXX XXXXXXXX
    XXXXXX XXXXXXXXXX X
        XXXXX XXXXXXX X XXXXX
        XXXXX XXXX X XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX X XXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXX XXXXXX
        XX XXXXXX
    XX
X

XX XXXX XXX XXX XX XXXXX XXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XX XXXXXXXX XX XXXXXXX XXX XXXXXX XXX XXXX
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX X
        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XX XXXXXX XXXX XX XXXXXX XX X XXXX XXXX XXXXXX XX XXXXXXX XXXXXXXXXX
        XX XXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX
        X
        
        XX XXXX XXXXXXX XXXXX XXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXX XXX XXXXXXX XXX XXXX XXX XXXXXX XXXXXXXXX XX XXXXXX XXXXXXX XXXXXXX
        XX XXX XXXXX XXXXXXX XXX XXXXXXXXXXX XXXXXXXXX XX XXX XXX
        XXXXX XXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        
        XX XXXXXX XXXX XXXXXXXXX XXXX XXXXXXXXX XX XXXXX XXXX XXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXX XXX XXX XXX XXXXXXX XXXXXXXX XXX XXXXX XXXXXXX XXXXXXXXXXX XX XXX XXX
        XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXX XXXXXXXXXXX XXXXXXXXX XXXX XX XXX XXXXX XXXXXXX
        XXXXX XXXXXXXX X XXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        
        XX XXX X XXXXXXXXX XX XXXXXXX XXXXXXX XXXX XXXXX XXXX XXXXXX
        XX XXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        X
        
        XX XXXX XXX XXXX XXXXXXX XXXX XXX XXXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX X
                XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XX
            XX XXXXXXX XXXXXXX XXXX XXXXX XXXX XXXXXX
            XXXXXX XXXXXXXXXX
        XX
        XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
        XXXXXXXXXX XX X
            XX XXXX XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XX XXXX XXXXXXXXXX XXXX XXXXXXX XXXXXX XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXX X XXXXXXX
            XXX
            
            XX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX X XX X
                XX XX XXXX XXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                
                XX XXXXX XXXXXXXX XXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
                
                XX XXX XXX XXXX XXXX XXXXXXX XXXX XXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                    XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXX X X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXX
                            XXXX
                        XXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX
                            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Sale') 
                                XXXX
                                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Payment') 
                                XXXX
                            XXXXXX
                        XXXXX
                    XX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX
                
                XX XXXX XXX XXXXX XXXXX XX XXXXXX XXXXXXX
                XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXX
                XXXXXXXXXXXXXXXXXXXXXX X X gettext(u'Showing all')  XXXXXXXXXXXXXXXXXXX  gettext(u'matching customers') XX
                XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                
            X XXXX X
                XX XX XXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
            X
        XX
        XXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX
    XX XXXXX XX XXXXX XXXXX
    
    XX XXXXXXXXXX XXXXXX XXXXX XX XXX XXXXXXXXXX XXXXXXXXXX XXX XXXX XXXXXX XXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX  XX XXXXX XXXXXXX XX XXXXX XXXXXXX XXXXXX
        X
    X
    
    XX XXXXXX XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXX
    XXX
    
    XX XXXXXX XXX XXXXXX XXXX XXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XX XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXX
        X XXXX X
            XX XX XXXXXX XXXXX XX XXXXXXXX XXXXXX XXX XXXX XX XXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
        X
    XXX
    
    XX XXXXX XXXXXX XXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX X
        XX XXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX X XXX
        XX XX X XXXX XXXX XXXXXX XX XXXXXXX XXXXXXXXXX XXXXXXX XX XXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
    XX
    
    XX XXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    X
    
    XX XXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    X
    
    XX XXX XXXXXXX XXXXXX XX XXX XXXXXXXX XXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX
    
    XX XXXXX XXX XXXXXX XXXXX XX XXXX XXXX
    XXXXXXXXXXXXXXXXXXXX
XXX
XXXXXXXXX

BB BBBBBBBBB
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
XXXXXXXXX
BBBBB
BBBBBBBB