BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBB BBBBBBBBBBBBBBBBXXXXBBBBXXXBBBBB XXXXXXXX X XXXXX XXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXXX
    XXX XXXXXXXXXXX
        XX XXXXXXXXXX XXXBB BBBBBBBBBBBBBBBBXXXXBBBBXXXXXXXXXXXBBBBB XXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBXXXXBBBBXXXBBBBB XXXXXXXX
    XXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXX
            XX XXXXXXBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX
            XXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX
                    BBBBBBBBBB
                    
                    XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            FFFFFFFFFFFFFFF
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            FFFFFFFFFFFFFFF
                        XXXXXX
                    XXXXXX
                    
                    XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXX
                            FFFFFFFFFFFFFFF
                        XXXXXX
                    XXXXXX
                    
                    XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXX
                            FFFFFFFFFFFFFFF
                        XXXXXX
                    XXXXXX
                    
                    XXXX XXXXXXXXXXX XXXXXXXXXX
                        XX XXXXXXBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                        XXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                            BB BBBBBBBBBBBBBBBBXXXXXXBBBBXXXXBBBBB XXXXXXXX
                        XXXXXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB