BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBB

BBBBB BBBBBXXXXXXXX XXXX XXXXXX X XXXXX XXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXX
            XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XX XXXXXXXXX
            XXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXX XXXXXXXXX XXXX XXX
XXXX XXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX XXXXX XXX XXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    BBB BBBBB BB BBBBBBBBBBBBB
                        XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXXXBBBBBX
                            
                        XXXXXXXXX
                    BBBBBB
                XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    BBB BBBB BB BBBBBBBBBBBB
                        XXXXXXX XXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBX
                            
                        XXXXXXXXX
                    BBBBBB
                XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXX
                XXXXXXXXX
            XXXXXX
        XXXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXX XXXX XXXXXXX XXX XXXXXX XXXXXXX XXX
XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXX XXXX XXX  XXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XX XXXXX
            XXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX XXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XX X XXXXXXX XXXXXXX XXXXXXX XXXXX XXXXXXXX XXX XXXXX XXXX XXX XXX XXXXXXXX XXXXXXXX
            XXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXX
                    XXXX
                        XXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                        XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                        XXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX
                        XXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                        XXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX
                    XXXXX
                    XXXX
                        BBB BBB BB BBBBBBBBBBBBBBBBBBBB
                        XXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        BBBBBB
                    XXXXX
                XXXXXXXX
                XXXXXXX
                    BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    BBB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB
                        BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                            BBB BBBBBBBBB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB
                                XXXX
                                    BB BBBBBBBB BB B
                                        XXX XXXXXXXXXFFFFFFX XXXXXXXXXXXXXXXXXXXXX
                                            XXXXXXXXXXXXXXXXX
                                        XXXXX
                                    BBBBB
                                    
                                    XXX XXXXXXXXXXXXXXXXXXXX
                                        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXX
                                    
                                    BBB BBB BB BBBBBBBBBBBBBBBBBBBB
                                        XXX XXXXXXXXXXXXXXXXXXXX
                                            BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                                BB BBBBBBBB B BFFFFFFFFFFFFFBBBBXBBBBB
                                            BBBBBBB
                                        XXXXX
                                    BBBBBB
                                    
                                    XXX XXXXXXXXXXXXXXX XXXXXXXXXFFFFFFFFFFFFFXXXXX
                                    XXX XXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXX
                                    
                                    BB BBBBBBBB BB B
                                        XXX XXXXXXXXXFFFFFFX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX
                                            XFFFFFFFFFFFFF
                                        XXXXX
                                        XXX XXXXXXXXXFFFFFFX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX
                                            XFFFFFFFFFFFFF
                                        XXXXX
                                    BBBBB
                                XXXXX
                            BBBBBB
                        BBBBBBB
                    BBBBBB
                    BBBBBBB
                XXXXXXXX
            XXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBB B B
            XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXX FFFFFFFFFFFFFFFF XXX XX FFFFFF XXXXXXXXXX XXXXXXXX XXX XXXXXX XXX XXXXXXXX XXXXXXXXX
            XXXXXX
            BBBBB
        XXXXXX
        BBBB
        XXXX XXXXXXXXXXXXXXXXXX XXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXX
            XX XXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXX XXX XXX XXXXXXXX XXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X XXXXXXXXX XXXXX XX XXX XXXX XXXXX XXXXXXXX
            XXXX XXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXX
                XXXX
                XX XXXXXXBBB BBBBBBBBBBX XXXXXXXXXX XXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXX XXX XXXX
                XXXX
            XXXXXX
        XXXXXX
        BBBBB
    XXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXXXXXX
XX XX XXXXXX XXXXXXX XXXXXX XXXX XX
XXXXXXXXX
BBBBBBBB