BBBBBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB X  gettext(u'Dairy Manager') BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXXX
    XXX XXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX 
    XXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX 
            XXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXX
                
                BB BBBBBBBBBBBBBBBBBB B B BB BBBBBBBBBBBBBBBBBBBBB B B
                XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX XXXX
                    XXX XXXXXXXXXXX XXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBB B B
                        XXXX FFFFFFFFFXXXXX
                        BBBBB
                        BB BBBBBBBBBBBBBBBBBBBBB B B
                        XXXX FFFFFFFFFXXXXX
                        BBBBB
                    XXXXX
                    XX XXXXXXXXXXX XXXXXXXXXX
                XXXXXX
                BBBBB
                
                XXXXX XXXXXXXXXXXXXX
                    BBBBBBBBBB
                    XXXX XXXXXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXX 
                        XXXXXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB