BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBXXXXX XXXXXX X XXXXX XXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXXXXXX
XXXXXX

XXXX XXXX XXXXX XXXXXX XXX
XXXX XXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXX
                FFFFFFFFFFFFFFF
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                FFFFFFFFFFFFFFF
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXX
                XXXXXXXXX
            XXXXXX
        XXXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXX XXXX XXX
BB BBBBBBBBBBB
XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXX FFFFFFF FF FF XX FFFFFFF FF FFXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXX
                    XXXX
                        XXXXXXXXXXXXX
                        XXXXXXXXX XXXXXXXX XXXXXXXX
                        XXXXXXXX XXXXXXXXXX
                        XXXXXXXXX XXXXXX XXXXXXXX
                    XXXXX
                XXXXXXXX
                XXXXXXX
                    BBB BBBBBBBB BB BBBBBBBBBBB
                    XXXX
                        XXXXFFFFFFF FF FFXXXXX
                        XXXXFFFFFFFFFFFFFXXXXX
                        XXXX
                            BBB BBBBBBBBBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                FFFFFFFFFFFFF X XXFFFFFFFFFFFFFX
                            XXXXXX
                            BBBBBB
                        XXXXX
                        XXX XXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXX
                    XXXXX
                    BBBBBB
                XXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXX
                        XXXXXXXXXXXXXXXX
                        XXXXFFFFFFFFFFFFF XXXXXX
                        XXXXFFFFFF XXXXXXXXXXX
                        XXXXXFFFFFFFFFFFFFXXXXX
                    XXXXX
                XXXXXXXX
            XXXXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXX XXXXX XXXXXXXXX XXX
XXXX XXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
XXXXXX
BBBB
XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
        XX XXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXX
        XX XXXXXXXXXXXXXXX XXXXX XXXX XXXXXXXXX XXX XXX XXXXXXXX XXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X XXXXXXXXX XXXX XXXXX XX XXXXXX XXXXX XXX XXXX XXXXXXXXXX
    XXXXXX
XXXXXX
BBBBB
BBBBBBBB

BBBBB BBBBBBB
BB BBBBBBBBBBB
XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XX XXXXXXX XXXX
    XXXXX XXXXX X XBBB BBBBBBBB BB BBBBBBBBBBBXFFFFFFF FF FFXXBBBBBBXX
    XXXXX XXXXXXXXXX X XBBB BBBBBBBB BB BBBBBBBBBBBXBBBBBBXX
    XXXXX XXXXXXX X XBBB BBBBBBBB BB BBBBBBBBBBBXBBBBBBXX
    
    XX XXXXXXX XXXXXX XX XXXX XXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX
    
    XXXXX XXXXXXXXXXXXXXX X XXX XXXXXXXXXX X
        XXXXX XXXXXX
        XXXXX X
            XXXXXXX XXXXXX
            XXXXXXXXX X
                X
                    XXXXXX XXXXXXXXX XXXXX
                    XXXXX XXXXXXXXXXX
                    XXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXX XXXXXX
                    XXXXXXXXXXXX XXXXXXXXX XXXX XXX XXXX
                    XXXXXXXXXXXX XX
                    XXXXXXXX XXX
                XX
                X
                    XXXXXX XXXXXXX XXXXX
                    XXXXX XXXXXXXX
                    XXXXX XXXXXXX
                    XXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
                    XXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXX
                    XXXXXXXXXXXX XX
                    XXXXX XXXXXX
                    XXXXXXXXXXXX XX
                    XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXX
                    XXXXXXXX XXXX
                X
            X
        XX
        XXXXXXXX X
            XXXXXXXXXXX XXXXX
            XXXXXXX X
                XX X
                    XXXXXXXXXXXX XXXXX
                    XXXXXXXXX XXXXXXX
                    XXXXXX X
                        XXXXXXXX XXXXX
                        XXXXX XXXXXXXXX XXXX
                    X
                XX
                XXX X
                    XXXXXXXXXXXX XXXXX
                    XXXXXXXXX XXXXXXXX
                    XXXXXX X
                        XXXXXXXX XXXXX
                        XXXXX XXXXXXX XXXX
                    XX
                    XXXXX X
                        XXXXXXXXXXXXXXXX XXXXX
                    X
                X
            XX
            XXXXXXXX X
                XXXXXX X
                    XXXXXXXX XXXXX
                    XXXXX XXXXXX XXXXX XXXXXXXXX
                XX
                XXXXXXXX X
                    XXXXX XXXXXXXX
                    XXXXXXXXXX XXXXX
                X
            X
        X
    XXX
XXX
XXXXXXXXX
BBBBB
BBBBBBBB