BBBBBBB BBBBBBBBBBB

BBBBB BBBBBXXXXX X XXXXXXXX XXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XX XXXXXXXX XXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXX
                XXXXX XXXXXXXXXXXXXX
                    BBBBBBBBBB
                    
                    XXXX XXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
                        XXXXXX
                    XXXXXX
                    
                    XXXX XXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                        XXXXXX
                    XXXXXX
                    
                    XXXX XXXXXXXXXXXXX XXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                        XXXXXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB