BBBBBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Delete Milk Type')  X  gettext(u'Dairy Manager') BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXXX
    XXX XXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX  gettext(u'Delete Milk Type') 
    XXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Back to List') 
            XXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
                XXX XXXXXXXXXXXXX gettext(u'Confirm Delete') XXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXX
                XXX XXXXXXXXXXXXX gettext(u'Are you sure you want to delete this milk type?') XXXXX
                XX XXXXXXXXXXXXX XXFFFFFFFFFFFFFX gettext(u'liter') XXXXX
                XX XXXXXXXXXXXXXXXXXXX gettext(u'This action cannot be undone. All related records will remain, but will reference a deleted milk type.') XXXX
                
                XXXXX XXXXXXXXXXXXXX
                    BBBBBBBBBB
                    XXXX XXXXXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Cancel') XXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Delete Permanently') 
                        XXXXXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB