BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB BBBBBBBBBBBBBBBB gettext(u'Edit') BBBB gettext(u'Add') BBBBB  gettext(u'Milk Type')  X  gettext(u'Dairy Manager') BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXXX
    XXX XXXXXXXXXXX
        XX XXXXXXXXXX XXXBB BBBBBBBBBBBBBBBBXXXXBBBBXXXXXXXXXXXBBBBB XXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBB gettext(u'Edit') BBBB gettext(u'Add') BBBBB  gettext(u'Milk Type') 
    XXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Back to List') 
            XXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX
                    BBBBBBBBBB
                    
                    XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            FFFFFFFFFFFFFFF
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            FFFFFFFFFFFFFFF
                        XXXXXX
                    XXXXXX
                    
                    XXXX XXXXXXXXXXX XXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Cancel') XXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                            BB BBBBBBBBBBBBBBBB gettext(u'Update') BBBB gettext(u'Save') BBBBB  gettext(u'Milk Type') 
                        XXXXXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB