BBBBBBB BBBBBBBBBBB

BBBBB BBBBBXXXXXX XXXX XXXX X XXXXX XXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXXX
    XXX XXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXX XXXX
    XXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XX XXXX
            XXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXX
                XXX XXXXXXXXXXXXXXXX XXX XXXX XXX XXXX XX XXXXXX XXXX XXXX XXXXXXXXXX
                XX XXXXXXXXXXXXX XXFFFFFFFFFFFFFXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XX XXXXXXX XXX XXXXXXX XXXXXXX XXXX XXXXXXX XXX XXXX XXXXXXXXX X XXXXXXX XXXX XXXXXXXXX
                
                XXXXX XXXXXXXXXXXXXX
                    BBBBBBBBBB
                    XXXX XXXXXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
                        XXXXXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB