BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBXXXXXXX XXXXXX X XXXXX XXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXX
XXXXXX

XXXX XXXX XXXXX XXXXXX XXX
XXXX XXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXX
                FFFFFFFFFFFFFFF
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                FFFFFFFFFFFFFFF
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXX
                XXXXXXXXX
            XXXXXX
        XXXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXX XXXX XXX
BB BBBBBBBBBBB
XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXX FFFFFFF FF XX FFFFFFF FFXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXX
                    XXXX
                        XXXXXXXXXXXXXX
                        XXXXXXXXX XXXXXXXX XXXXXXXX
                        XXXXXXXXX XXXXXX XXXXXXXX
                        XXXXXXXXXXXX XXXXXXXX
                        XXXXXXXXXXX XXXXXXXX
                    XXXXX
                XXXXXXXX
                XXXXXXX
                    BBB BBBBBBBBBB BB BBBBBBBBBBB
                    XXXX
                        XXXXFFFFFFF FFXXXXX
                        XXXXFFFFFFFFFFFFFXXXXX
                        XXXXFFFFFFFFFFFFFXXXXX
                        XXXXFFFFFFFFFFFFFXXXXX
                        XXX XXXXXXXBB BBBBBBBBBBBBBBBBBB B BXXXXXXXXXXXXBBBB BBBBBBBBBBBBBBBBBB B BXXXXXXXXXXXBBBBB XXXXXXXXX
                            FFFFFFFFFFFFF
                        XXXXX
                    XXXXX
                    BBBBBB
                XXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXX
                        XXXXXXXXXXXXXXXX
                        XXXXFFFFFFFFFFFFF XXXXXX
                        XXXXXFFFFFFFFFFFFFXXXXX
                        XXXXXFFFFFFFFFFFFFXXXXX
                        XXXXXFFFFFFFFFFFFFXXXXX
                    XXXXX
                XXXXXXXX
            XXXXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXX XXXXX XXXXXXXXX XXX
XXXX XXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
XXXXXX
BBBB
XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
        XX XXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXX
        XX XXXXXXXXXXXXXXX XXXX XXXXXXXXX XXX XXX XXXXXXXX XXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X XXXXXXXXX XXXX XXXXX XX XXXXXX XXXXX XXX XXXX XXXXXXXXXX
    XXXXXX
XXXXXX
BBBBB
BBBBBBBB

BBBBB BBBBBBB
BB BBBBBBBBBBB
XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XX XXXXXXX XXXX
    XXXXX XXXXXX X XBBB BBBBBBBBBB BB BBBBBBBBBBBXFFFFFFF FFXXBBBBBBXX
    XXXXX XXXXX X XBBB BBBBBBBBBB BB BBBBBBBBBBBXBBBBBBXX
    XXXXX XXXXXXXX X XBBB BBBBBBBBBB BB BBBBBBBBBBBXBBBBBBXX
    XXXXX XXXXXXXX X XBBB BBBBBBBBBB BB BBBBBBBBBBBXBBBBBBXX
    
    XX XXXXXXX XXXXXX XX XXXX XXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    
    XXXXX XXXXXXXXXXXX X XXX XXXXXXXXXX X
        XXXXX XXXXXX
        XXXXX X
            XXXXXXX XXXXXXX
            XXXXXXXXX X
                X
                    XXXXXX XXXXXX XXXXX
                    XXXXX XXXXXX
                    XXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXX XXXXXX
                    XXXXXXXXXXXX XXXXXXXXX XXXX XXX XXXX
                    XXXXXXXXXXXX X
                XX
                X
                    XXXXXX XXXXXXXXX XXXXX
                    XXXXX XXXXXXXXX
                    XXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
                    XXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXX
                    XXXXXXXXXXXX X
                XX
                X
                    XXXXXX XXXXXXXX XXXXX
                    XXXXX XXXXXXXXX
                    XXXXX XXXXXXX
                    XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XX XXXXXX
                    XXXXXXXXXXXX XXXXXXXXXX XXXX XX XXXX
                    XXXXXXXXXXXX XX
                    XXXXX XXXXXX
                    XXXXXXXXXXXX XX
                    XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XX XXX
                X
            X
        XX
        XXXXXXXX X
            XXXXXXXXXXX XXXXX
            XXXXXXX X
                XX X
                    XXXXXXXXXXXX XXXXX
                    XXXXXX X
                        XXXXXXXX XXXXX
                        XXXXX XXXXXXX XXXX
                    X
                X
            XX
            XXXXXXXX X
                XXXXXX X
                    XXXXXXXX XXXXX
                    XXXXX XXXXXXXX XXXXXX XXXXXXXX XXX XXXXXXXX
                XX
                XXXXXXXX X
                    XXXXX XXXXXXXX
                    XXXXXXXXXX XXXXX
                X
            X
        X
    XXX
XXX
XXXXXXXXX
BBBBB
BBBBBBBB