BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBB BBBBBBBBBBBBBBBBXXXXBBBBXXXBBBBB XXXXXXX X XXXXX XXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXXX
    XXX XXXXXXXXXXX
        XX XXXXXXXXXX XXXBB BBBBBBBBBBBBBBBBXXXXBBBBXXXXXXXXXXXBBBBB XXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBXXXXBBBBXXXBBBBB XXXXXXX
    XXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XX XXXX
            XXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                BB BBB BBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXX XXXXXX XXXXXXX XXX
                XXXX XXXXXXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXX
                        XXXXXXXXX
                    XXXXXX
                    
                    BB BBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXX
                        BBB BBBBBB BB BBBBBBBBBBBBBB
                        XX XXXXXXBBB BBBBBBBBBBBBBXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                            
                        XXXX
                        BBBBBB
                    XXXXXX
                    BBBBB
                XXXXXX
                BBBB
                XXXXX XXXXXXXXXXXXXX
                    BBBBBBBBBB
                    
                    XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            BB BBBBBBBBBBBBBBBBBB BB BBBBBBBB
                                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXX
                                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
                                        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
                                        XX XXXXXXBBB BBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                            XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
                                        XXXX
                                    XXXXXX
                                XXXXXX
                            BBBBB
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            FFFFFFFFFFFFFFF
                        XXXXXX
                    XXXXXX
                    
                    XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            FFFFFFFFFFFFFFF
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            FFFFFFFFFFFFFFF
                        XXXXXX
                    XXXXXX
                    
                    XXXX XXXXXXXXXXX XXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                            BB BBBBBBBBBBBBBBBBXXXXXXBBBBXXXXBBBBB XXXXXXX
                        XXXXXXXXX
                    XXXXXX
                XXXXXXX
                BBBBB
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
            XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        XX XXXXXX
    X
XXX

XXXXXXXX XXXXXXXXXXXXXX XXXXX X
    XXX XXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX X XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX XXXXXX XXXXXX
    XX
X
XXXXXXXXX
BBBBBBBB