BBBBBBB BBBBBBBBBBB

BBBBB BBBBBXXXXXXXX X XXXXXXXX XXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXX XXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXX
                XXXXX XXXXXXXXXXXXXX
                    BBBBBBBBBB
                    
                    BB BBBBBBBBBBB
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXXXXXX XXXXXXX XXX XXXXXX XXXXXXXXXX
                        XXXX
                            BBB BBBBBB BBBBBB BB BBBBBBBBBBBBBBBBB
                                BBB BBBBB BB BBBBBB
                                XXXXXXXXX
                                BBBBBB
                            BBBBBB
                        XXXXX
                    XXXXXX
                    BBBBB
                    
                    XXXX XXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
                        XXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX XX XXXXXX XXXXXXXX XXXXXX XXX XXXXXXXXX XXXXXXXXXXXXX
                    XXXXXX
                    
                    XXXX XXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                        XXXXXX
                    XXXXXX
                    
                    XXXX XXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                        XXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXX XXXX XXXXXXX XX XXXXX X XXXXXXXXXX XXX XXXXX XX XXXXXXXX XXXXXXXX
                        XXXXXXXX
                    XXXXXX
                    
                    XXXX XXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                        XXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX XXXX XXXXXXXX XX XXXXXXX XXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    
                    XXXX XXXXXXXXXXXXX XXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXX
                        XXXXXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXX XX XXXXXXXX XX XXXXXXBBB BBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB