BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Batch Sale Input')  X  gettext(u'Dairy Manager') BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXXX
    XXX XXXXXXXXXXX
        XX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX
         gettext(u'Batch Sale Input') 
    XXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXX
            XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Back to List') 
            XXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXX gettext(u'Quick Input Format') XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'How to use batch input') XXXXX
            XX XXXXXXXXXXXXX gettext(u'Enter quantities and milk types using the format:') XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'quantity-quantity-milk_type_code') XXXX
            XX XXXXXXXXXXXXXXXXXXXXX gettext(u'Example:') XXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'means 1 liter of Cow milk and 2 liters of Buffalo milk.') XXXX
            XX XXXXXXXXXXXXXXXXXXXXX gettext(u'Available milk types for selected customer:') XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXX gettext(u'Please select a customer to see their assigned milk types.') XXXX
            XXXXXX
        XXXXXX
        XXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Cancel') XXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                     gettext(u'Save Sales') 
                XXXXXXXXX
            XXXXXX
        XXXXXXX
    XXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBBB
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXXXX XX XXXXXX XXXXXXXXX XXXX XXXXX XXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
            XX XXXXXXXXXXXXXXXXXXXXXX X
                XX XXXXX XXXX XXXXX XXX XXXXXXXX XXXXXXXX
                XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXX XX X
                        XX XXXXXXXXXXXXXX X
                            XXXXX XXX XXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
                        X
                        XXXXXX XXXXXXXXXXXXXXXX
                    XX
                    XXXXXXXXXX XX X
                        XX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXX X XX X
                            XX XXXXXXX XXXXXXXXXX XXXX XXXXX XXXX XXXXX
                            XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX 
                                XXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
                        X XXXX X
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXX gettext(u'No milk types assigned to this customer.') XXXXXX
                        X
                    XX
                    XXXXXXXXXXXX XX X
                        XXXXXXXXXXXXXXXXXXXXX XX XXXXX XXXX XXXXXXXX XXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Error loading milk types') XXXXXX
                    XXX
            X XXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXX gettext(u'Please select a customer to see their assigned milk types.') XXXXXX
            X
        X
        
        XX XXXXXX XXXX XXXXX XXXX XXXXXXXX XXXXXXXXX XXXXXXX
        XX XXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XX XXXXXXXXXX XX XXXX XXXX XX X XXXXXXXX XX XXXXXXX XXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        X
    XXX
XXXXXXXXX
BBBBBBBB