BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBXXXXX XXXX XXXXX X XXXXX XXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXXX
    XXX XXXXXXXXXXX
        XX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX
        XXXXX XXXX XXXXX
    XXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXX
            XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XX XXXX
            XXXX
            XX XXXXXXBBB BBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXX XXXX
            XXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXX XX XXX XXXXX XXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXX XXXXX XXXXX XXX XXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX X XXXXX XX XXX XXXX XXX X XXXXXX XX XXXXXXX XXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXX XXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X XXXXXXXX XX XXX XXXXX XXXXXXXX XXXX XXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB
            
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                    XXXX XXXXX
                XXXXXXXXX
            XXXXXX
        XXXXXXX
    XXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBBB
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXXXX XX XXXXXX XXXXXXXXX XXXX XXXXX XXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
            XX XXXXXXXXXXXXXXXXXXXXXX X
                XX XXXXX XXXX XXXXX XXX XXXXXXXX XXXXXXXX
                XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXX XX X
                        XX XXXXXXXXXXXXXX X
                            XXXXX XXX XXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
                        X
                        XXXXXX XXXXXXXXXXXXXXXX
                    XX
                    XXXXXXXXXX XX X
                        XX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXX X XX X
                            XX XXXXXXX XXXXXXXXXX XXXX XXXXX XXXX XXXXX
                            XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX 
                                XXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
                        X XXXX X
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXX XX XXXX XXXXXXXXXXXXXXX
                        X
                    XX
                    XXXXXXXXXXXX XX X
                        XXXXXXXXXXXXXXXXXXXXX XX XXXXX XXXX XXXXXXXX XXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXX
                    XXX
            X XXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X XXXXXXXX XX XXX XXXXX XXXXXXXX XXXX XXXXXXXXXXXX
            X
        X
        
        XX XXXXXX XXXX XXXXX XXXX XXXXXXXX XXXXXXXXX XXXXXXX
        XX XXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XX XXXXXXXXXX XX XXXX XXXX XX X XXXXXXXX XX XXXXXXX XXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        X
    XXX
XXXXXXXXX
BBBBBBBB